Write a function that determines whether a number is equal to the sum of its divisors minus the number itself.

Use this function to display all numbers with the required property up to a given n.

In [1]:
def generate_divisors(number: int) -> list:
    """
    This function generates the divisors of a number:
    :param number: is the number for which divisors are generated
    :returns: a list of all divisors of the parameter
    """
    return [x for x in range(1, number) if number % x == 0]

def check_number(number: int) -> bool:
    """
    This function checks whether the number given as a parameter has the sum of its divisors equal to it:
    :param number: is the number for which the condition is checked.
    :returns: True if the condition is met, False if not
    """
    return sum(generate_divisors(number)) == number

def find_numbers(number_limit: int) -> list:
    """
    This function finds the numbers, up to a given number, that meet the requirement condition:
    :param number_limit: is the limit up to which to search for numbers that satisfy the condition.
    :returns: list of numbers found
    """
    return [number for number in range(1, number_limit + 1) if check_number(number) == True]

print(generate_divisors.__doc__)
print(check_number.__doc__)
print(find_numbers.__doc__)
print(*find_numbers(2000), sep = ", ")
print(*find_numbers(100), sep = ", ")


    This function generates the divisors of a number:
    :param number: is the number for which divisors are generated
    :returns: a list of all divisors of the parameter
    

    This function checks whether the number given as a parameter has the sum of its divisors equal to it:
    :param number: is the number for which the condition is checked.
    :returns: True if the condition is met, False if not
    

    This function finds the numbers, up to a given number, that meet the requirement condition:
    :param numberLimit: is the limit up to which to search for numbers that satisfy the condition.
    :returns: list of numbers found
    
6, 28, 496
6, 28


Write a function that determines whether or not a string - assumed to be spelled with small letters - is palindromic.
A palindrome is a string of characters that read from right to left has the same content as reading from left 
to right. Depending on the value of a boolean flag ignore_spaces, with default value False, will ignore
(eliminate) or not ignore spaces. If the string given as a parameter does not have all lower case letters, an exception will be thrown; documentation exceptions in Python.

Examples: <br>
is_palindrome('they make coffees', ignore_spaces=True) returns True; is_palindrome('they make coffees') returns False. <br>
is_palindrome('They make coffees') throws an exception, regardless of the value of ignore_spaces. <br>
is_palindrome('abaac') returns False <br>

In [2]:
def is_palindrome(my_string: str, ignore_spaces: bool=False) -> bool:
    """
    Function that determines whether or not a string of characters - assumed to be written in small letters - is palindromic
    :param my_string: holds string
    :param ignore_spaces: holds whether or not to remove spaces
    :returns: True if palindrome and False otherwise
    :raises Exception: Exception if there is a capital letter in the string
    """
    if any(character.isupper() for character in my_string) is True:
        raise Exception("Only lower characters allowed")
        
    if ignore_spaces is True:
        my_string = my_string.replace(" ", "")
        
    return my_string == my_string[::-1]


print(is_palindrome('ele fac cafele', ignore_spaces=True))
print(is_palindrome('ele fac cafele'))
#is_palindrome('Ele fac cafele')
print(is_palindrome('abaac'))
print(is_palindrome.__doc__)

True
False
False

    Function that determines whether or not a string of characters - assumed to be written in small letters - is palindromic
    :param my_string: holds string
    :param ignore_spaces: holds whether or not to remove spaces
    :returns: True if palindrome and False otherwise
    :raises Exception: Exception if there is a capital letter in the string
    


Write a function that gets paths to two text files, each of which is known to have a number.
per line (the number of lines in the files is unknown apriori). The function will return a tuple with: the list of numbers that appear in
both files and the maximum difference that exists between the numbers in the second file and the numbers in the first file. The numbers can
be signed, integer or floating point (the function must work in any situation). Try using functions
predefined Python functions (or NumPy) and collection comprehension.
    
Example: a.txt contains the numbers 1, 2, 3, 4 (one per line). b.txt contains 2, 3, 4, 10 (one number per line).

The function will return the tuple ([2, 3, 4], 9). The number 9 is made by 10-1.

In [5]:
def read_file(path: str):
    """
    This function reads a file with a specified path
    :param path: file path
    :returns: the open file
    """
    return open(path, "r")
    
def intersection_of_lists(f, g) -> list:
    """
    This function returns a list of the intersection of two open files:
    :param1 f: first file
    :param2 g: second file
    :returns: list of the intersection of the elements in the two files
    """
    first_file: list = [int(number) for number in f.readlines()] 
    second_file: list = [int(number) for number in g.readlines()]
    f.seek(0)
    g.seek(0)
    
    return list(set(first_file).intersection(second_file))

def maximum_difference(list_of_elements:list) -> int:
    """
    This function returns the maximum difference in a string of numbers:
    :param1 list_of_elements: list of elements 
    :returns: maximum difference from list
    """
    return max(list_of_elements) - min(list_of_elements)

def concatenate_lists(f, g) -> list:
    """
    This function returns the entire list of numbers in both files:
    :param1 f: first file
    :param2 g: second file
    :returns: list of numbers in both files
    """
    first_file: list = [int(number) for number in f.readlines()] 
    second_file: list = [int(number) for number in g.readlines()]
    f.seek(0)
    g.seek(0)
    
    return first_file + second_file

def make_tuple(path1:str, path2:str) -> tuple:
    """
    This function returns a tuple consisting of the intersection of two lists and the maximum difference in a list:
    :param1 path1: path of the first file
    :param2 path2: path of the second file
    :returns: a tuple formed from the intersection of two lists and the maximum difference in a list
    """
    f = read_file(path1);
    g = read_file(path2);
    result: tuple = (intersection_of_lists(f,g), maximum_difference(concatenate_lists(f,g)))
    f.close()
    g.close()
    
    return result

print(make_tuple("Exercise2.1.txt", "Exercise2.2.txt"))

([2, 3, 4], 9)


Write a sum_divisors_digits function that takes a strictly positive natural number 𝑛 and returns the sum of the digits
of its divisors. In another black_hole function, sum_divisors_digits is repeatedly called on the resulting numbers,
until a maximum number of iterations is reached (default 1000) or the number 15 is reached. You can create other functions
auxiliary functions.

Example 1: start from 𝑛=15 ; the divisors are 1,3,5,15 ; the sum of the divisor digits is 1+3+5+1+5=15 , this is
the result of calling sum_divisors_digits(15). The black_hole function therefore stops after a single call of the function
sum_divisors_digits.

Example 2: start from 𝑛=21 ; the divisors are 1,3,7,21 and sum_divisors_digits(21) is 1+3+7+2+1=14 ; restart in
black_hole function the sum_divisors_digits function call until the number of calls is exhausted or potentially stabilized
in 15.

In [6]:
def check_number(number: int) -> bool:
    """
    Function that determines whether a number is positive or not
    :param number: holds the number
    :returns: True if positive and False otherwise
    """
    return (number >= 0)

def get_divisors(number: int) -> list:
    """
    Function that determines the divisors of a number
    :param number: holds the number
    :returns: list of divisors of the number
    """
    return [index for index in range(1, number + 1) if number % index == 0]

def sum_divisors_digits(number: int) -> int:
    """
    Function that determines the divisors of a number
    :param number: holds the number
    :returns: sum of the divisors of the number
    """
    divisors: list = get_divisors(number)
    
    return sum(list(map(lambda ele: sum(int(sub) for sub in str(ele)), divisors)))
    
def black_hole(number: int):
    """
    Function that displays after how many iterations the number 15 is reached, if reached
    :param number: retains the initial number
    """
    if(check_number(number) == False):
        print('Positive number needed!')
        return
    div_sum: int = number
    iteration: int = 0
    while iteration < 1000 and div_sum != 15:
        div_sum = sum_divisors_digits(div_sum)
        iteration += 1
    if div_sum == 15:
        print(f'Number 15 was reached after {iteration} iterations')
    else:
        print('After 1000 iterations, the divisor'f's sum of the initial number is: {div}')
        
        
black_hole(-41)
black_hole(15)
black_hole(21)

Positive number needed!
Number 15 was reached after 0 iterations
Number 15 was reached after 2 iterations


Write a function that receives two dictionaries and returns True if the first dictionary is contained in the second and
False otherwise. We say that a dictionary a is contained in dictionary b if all the keys in a are found among the keys in b.
and all for any key c in a, a[c] == b[c]. Try using predefined Python functions (any, all), types of
Python built-in data types and collection comprehension.

In [7]:
def check_keys(first_dictionary: dict, second_dictionary: dict) -> bool:
    """
    Function that returns if the first dictionary key is included in the second dictionary
    :param1: first_dictionary: first dictionary
    :param2: second_dictionary: second dictionary
    :returns: True if the keys of the first are in the second, False if not
    """
    return all(key in second_dictionary.keys() for key in first_dictionary.keys());

def check_keys_value(first_dictionary: dict, second_dictionary: dict) -> bool:
    """
    Function that returns whether the values of the common keys in both dictionaries are equal:
    :param1: first_dictionary: first_dictionary
    :param2: second_dictionary: second dictionary
    :returns: True if the common keys have the same values, False if not
    """
    return all(key in second_dictionary and second_dictionary[key] == first_dictionary[key] for key in first_dictionary);

def included_dictionary(first_dictionary: dict, second_dictionary: dict) -> str:
    if not check_keys(first_dictionary, second_dictionary) or not check_keys_value(first_dictionary, second_dictionary):
        return "The first dictionary is not included in the second dictionary" 
    return "The first dictionary is included in the second dictionary";

the_first_dict = {
  "brand": "Ford",
  "electric": False,
  "colors": ["red", "white", "blue"]
}

the_second_dict = {
  "brand": "Ford",
  "electric": False,
  "year": 1963,
  "colors": ["red", "white", "blue"]
}

print(included_dictionary(the_first_dict, the_second_dict))

The first dictionary is included in the second dictionary


Write a function that for a given vector 𝑎 returns the first order difference between its elements: 
𝑏[𝑖]=𝑎[𝑖+1]-𝑎[𝑖]. Then write another function that does the same thing for a matrix, on rows or columns.
                                                                      
Examples: <br>
a = np.array([1, 2, 10, 3]); diff1_vector(a) will return the vector NumPy with content (1, 8, -7). <br>
a = np.array([[1, 2, 3], [40, 50, 60]]); diff1_mat(a, axis=0) returns an array with a single line, [[39, 48, 57]]. diff1_mat(a, axis=1) returns an array with 2x2, [[1, 1], [10, 10]].

In [9]:
import numpy as np

def diff1_vector(array: list) -> list:
    """
    Function that determines the first order difference between elements of a vector
    :param number: vector
    :returns: difference
    """
    return np.diff(array)

def check_axis(axis: int) -> bool:
    """
    Function that determines if the axis coordinate is correct
    :param number: axis coordinate
    :returns: True if correct, False otherwise
    """
    return True if axis == 1 or axis == 0 else False

def diff1_mat(matrix: list, my_axis: int) -> list:
    """
    Function that determines the first-order difference between elements of a matrix, on rows or columns
    :param number: matrix and axis coordinate
    :returns: difference
    """
    if(check_axis(my_axis) == True):
        return np.diff(matrix, axis=my_axis)

    
a = np.array([1, 2, 10, 3])
b  = np.array([[1, 2, 3], [40, 50, 60]])
print(diff1_vector(a))
print(diff1_mat(b, 0))

[ 1  8 -7]
[[39 48 57]]


Write a function that finds the positions of local maxima in a numpy vector. A local maximum is a value that has in
immediate neighbours (current index ± 1, without leaving the vector) values strictly smaller than it.

Example: [-1, 3, -7, 1, 2, 6, 0, 1] -> [1, 5, 7].

In [11]:
import numpy as np

def get_position(array: list) -> list:
    """
    Function that returns the positions of local maxima in a given array:
    :param1: array: list given
    :returns: Numpy array with the positions of local maxima
    """
    result = np.array([index for index in range(1, len(array) - 1) if array[index] > array[index + 1] and array[index] > array[index - 1]]) 
    if(array[0] > array[1]):
        result = np.insert(result, 0, 0)
    if(array[len(array) - 1] > array[len(array)-2]):
        result = np.append(result, len(array) - 1) 
        
    return result

array = np.array([-1, 3, -7, 1, 2, 6, 0, 1])
print(get_position(array))

[1 5 7]


For a given vector NumPy, compute all windows of a given length with a given dilation. The length of a
means the number of elements in the resulting vectors, dilation is the number of neighbouring elements that are skipped in
building a "window".
    
Examples: <br>
v = np.arange(20), win_len=4, dilation=1 -> [0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], ...[16, 17, 18, 19]. <br>
v = np.arange(20), win_len=3, dilation=2 -> [0, 2, 4], [1, 3, 5], ..., [15, 17, 19] <br>
The default values for win_len and dilation are 3 and 1 respectively. You will check within the functions if: 
0 < win_len <= number of elements in vector, dilation > 0 and if for the input vector, win_len and dilation given 
results in at least one window; if any of these conditions is not met, do not execute the rest of the function and discard <br>
The result will be given as an array with win_len columns.

In [13]:
import numpy as np

def check_inputs(v: list, win_len: int, dilation: int) -> bool:
    """
    Function that checks the input
    :param v: hold array
    :param win_len: holds the number of elements in the resulting vectors
    :param dilation: represents over how many neighboring elements are skipped in building a "window"
    :returns: true if the check throws no exceptions
    :raises Exception: if one of the following conditions is not met: 0 < win_len <= number of elements in vector, dilation > 0 and if for the given input vector, win_len and dilation at least one window results
    """
    if dilation <= 0:
        raise Exception("Dilation must be bigger than 0")
    if win_len <= 0 or win_len > v.size:
        raise Exception("The length of the windows must be bigger than 0 and smaller than the size of the array")
    if win_len * dilation - dilation > v.size - 1:
        raise Exception("The given input doesn't result any window, please change your input")
        
    return True

def calculate_windows(v: list, win_len: int=3, dilation: int=1) -> list:
    """
    Function that calculates and displays windows of a certain length with a certain expansion
    :param v: hold array
    :param win_len: holds the number of elements in the resulting vectors
    :param dilation: represents over how many neighboring elements are skipped in building a "window"
    :returns: the resulting array if the "check_inputs" function does not throw an exception
    """
    check_inputs(v, win_len, dilation)
    arr: list = np.array([v[index:index + win_len * dilation:dilation] for index in range(0, v.size) if index + win_len <= v.size and len(v[index:index + win_len * dilation:dilation]) == win_len])
    print(arr)
        
        
v: list = np.arange(20)
win_len: int = 3
dilation: int = 2
calculate_windows(v, win_len, dilation)

[[ 0  2  4]
 [ 1  3  5]
 [ 2  4  6]
 [ 3  5  7]
 [ 4  6  8]
 [ 5  7  9]
 [ 6  8 10]
 [ 7  9 11]
 [ 8 10 12]
 [ 9 11 13]
 [10 12 14]
 [11 13 15]
 [12 14 16]
 [13 15 17]
 [14 16 18]
 [15 17 19]]


Download the Wine dataset described at http://archive.ics.uci.edu/ml/datasets/Wine, the wine.data file, and upload it
into a NumPy array, using np.genfromtxt. Randomly choose 35 positions within the array of values, set these to
NaN positions. Construct a function that, given an array as input, returns a collection of line indices of
columns in which Na values are found, as well as the 'corrected' matrix: the NaN values are filled with a default value given as
parameter of your function.

In [15]:
import numpy as np
import random
import sys

def put_nan(matrix: list, positions: list):
    """
    Function that replaces with Nan value the array values at some given positions:
    :param1: matrix: given array
    :param2: positions: positions in the array
    :returns: the changed array
    """
    for position in positions:
        matrix[position[0]][position[1]] = 'NaN';
        
def correct_matrix(matrix: list, correct_sign) -> list:
    """
    Function that replaces with a given sign the values of a given matrix having the value NaN and returns its positions
    :param1: matrix: the given matrix
    :param2: correct_sign: sign with which the matrix value should be replaced
    :returns: the positions of the matrix where the NaN value is located
    """
    matrix[matrix == 'NaN'] = correct_sign
    result = np.where(matrix == correct_sign);
    return [(result[0][index], result[1][index]) for index in range(len(result[0]))]

matrix = np.genfromtxt("wine.data", delimiter=",", dtype=str)
random_positions = [(random.randrange(0, len(matrix)), random.randrange(0, len(matrix[0]))) for i in range(35)]
put_nan(matrix, random_positions);
result = correct_matrix(matrix, '!')
print('The positions that were NaN are:', correct_matrix(matrix, '!'))
np.set_printoptions(threshold=sys.maxsize)
print('The corrected matrix is:')
print(matrix)

The positions that were NaN are: [(3, 0), (11, 5), (15, 3), (18, 3), (20, 0), (29, 9), (43, 10), (45, 0), (68, 3), (74, 4), (88, 9), (92, 10), (96, 6), (102, 1), (105, 3), (112, 3), (113, 11), (118, 3), (120, 6), (121, 11), (123, 10), (128, 2), (129, 3), (132, 8), (136, 10), (137, 12), (141, 0), (146, 0), (146, 2), (149, 1), (157, 11), (159, 0), (164, 7), (173, 5)]
The corrected matrix is:
[['1' '14.23' '1.71' '2.43' '15.6' '127' '2.8' '3.06' '.28' '2.29' '5.64'
  '1.04' '3.92' '1065']
 ['1' '13.2' '1.78' '2.14' '11.2' '100' '2.65' '2.76' '.26' '1.28' '4.38'
  '1.05' '3.4' '1050']
 ['1' '13.16' '2.36' '2.67' '18.6' '101' '2.8' '3.24' '.3' '2.81' '5.68'
  '1.03' '3.17' '1185']
 ['!' '14.37' '1.95' '2.5' '16.8' '113' '3.85' '3.49' '.24' '2.18' '7.8'
  '.86' '3.45' '1480']
 ['1' '13.24' '2.59' '2.87' '21' '118' '2.8' '2.69' '.39' '1.82' '4.32'
  '1.04' '2.93' '735']
 ['1' '14.2' '1.76' '2.45' '15.2' '112' '3.27' '3.39' '.34' '1.97' '6.75'
  '1.05' '2.85' '1450']
 ['1' '14.39' '1.87' '2.45

Given a vector v of floating point numbers, a floating point number x and an integer k>0, k<=len(v). 
Write a function that determines the positions of the k nearest neighbors of v with respect to x (k nearest neighbors, 1d).

In [17]:
import numpy as np

def nearest_neighbors(array: list, value: float, nbr_neighbors: int) -> list:
    """
    Function that determines the positions of the closest "nbr_neighbors" values in the "array" relative to "value".
    :param array: hold array
    :param value: holds the value for which we are looking for neighbors
    :param nbr_neighbors: holds the number of neighbors we will search for for "value"
    :returns: the index of the nearest neighbours
    """
    return np.argsort(np.array([np.linalg.norm(value-x) for x in array]))[:nbr_neighbors]

v: list = np.array([1.5, 2.02, 3.66, 13.12, 4.66, 3.00], dtype=np.float64)
x: float = 3.2
k: int = 3

print(nearest_neighbors(v, x, k))

[5 2 1]
